export const productsByIdResponseMock = [
  {
    productId: '3',
    productName: 'Tank',
    brand: 'New Offers!!',
    brandId: 2000045,
    brandImageUrl: null,
    linkText: 'tank-top',
    productReference: 'xpto123',
    productReferenceCode: 'xpto123',
    categoryId: '48',
    productTitle: 'Tank Top',
    metaTagDescription: 'Show your arms!',
    releaseDate: '1994-06-28T00:00:00',
    clusterHighlights: {
      '1182': 'Top Seller',
      '1970': 'Summer',
    },
    productClusters: {
      '1182': 'Top Seller',
      '1967': 'Collection without highlight',
      '1969': 'teste Ultimo SKU',
      '1970': 'Summer',
    },
    searchableClusters: {
      '1182': 'Top Seller',
      '1970': 'Summer',
    },
    categories: [
      '/Apparel & Accessories/Clothing/Tops/',
      '/Apparel & Accessories/Clothing/',
      '/Apparel & Accessories/',
    ],
    categoriesIds: ['/25/47/48/', '/25/47/', '/25/'],
    link: 'https://storecomponents.vtexcommercestable.com.br/tank-top/p',
    'On Sale': ['True'],
    Group: ['On Sale'],
    'Sleeve type': ['Sleeveless'],
    Specifications: ['Sleeve type'],
    allSpecifications: ['On Sale', 'Sleeve type'],
    allSpecificationsGroups: ['Group', 'Specifications'],
    description: 'Show your arms!',
    items: [
      {
        itemId: '3',
        name: 'White',
        nameComplete: 'Tank White',
        complementName: '',
        ean: '613468247360',
        referenceId: [
          {
            Key: 'RefId',
            Value: 'whitet',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1.0,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: '155642',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155642-#width#-#height#/Frame-1.jpg?v=637411554902130000" width="#width#" height="#height#" alt="Frame-1" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155642/Frame-1.jpg?v=637411554902130000',
            imageText: 'Frame-1',
            imageLastModified: '2020-11-16T20:31:30.2130000Z',
          },
        ],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://storecomponents.vtexcommercestable.com.br/checkout/cart/add?sku=3&qty=1&seller=1&sc=1&price=37577&cv=37F62B371F548B5302696581CADC7894_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                '0': {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'American Express',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'American Express à vista',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa à vista',
                },
                {
                  Value: 187.88,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 2 vezes sem juros',
                },
                {
                  Value: 125.25,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 3 vezes sem juros',
                },
                {
                  Value: 93.94,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 4,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 4 vezes sem juros',
                },
                {
                  Value: 75.15,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 5,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 5 vezes sem juros',
                },
                {
                  Value: 62.62,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 6,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 6 vezes sem juros',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Diners',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Diners à vista',
                },
                {
                  Value: 190.7,
                  InterestRate: 1.0,
                  TotalValuePlusInterestRate: 381.4,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Diners',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Diners 2 vezes com juros',
                },
                {
                  Value: 130.3,
                  InterestRate: 2.0,
                  TotalValuePlusInterestRate: 390.9,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Diners',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Diners 3 vezes com juros',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard à vista',
                },
                {
                  Value: 187.88,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 2 vezes sem juros',
                },
                {
                  Value: 125.25,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 3 vezes sem juros',
                },
                {
                  Value: 93.94,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 4,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 4 vezes sem juros',
                },
                {
                  Value: 75.15,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 5,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 5 vezes sem juros',
                },
                {
                  Value: 62.62,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 6,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 6 vezes sem juros',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Boleto Bancário',
                  PaymentSystemGroupName: 'bankInvoicePaymentGroup',
                  Name: 'Boleto Bancário à vista',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Vale',
                  PaymentSystemGroupName: 'giftCardPaymentGroup',
                  Name: 'Vale à vista',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Promissory',
                  PaymentSystemGroupName: 'promissoryPaymentGroup',
                  Name: 'Promissory à vista',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit à vista',
                },
                {
                  Value: 187.88,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 2 vezes sem juros',
                },
                {
                  Value: 129.01,
                  InterestRate: 1.0,
                  TotalValuePlusInterestRate: 387.03,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 3 vezes com juros',
                },
                {
                  Value: 375.77,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 375.77,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Free',
                  PaymentSystemGroupName: 'custom201PaymentGroupPaymentGroup',
                  Name: 'Free à vista',
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [
                {
                  '<Name>k__BackingField': '8% Boleto',
                  '<Conditions>k__BackingField': {
                    '<MinimumQuantity>k__BackingField': 0,
                    '<Parameters>k__BackingField': [
                      {
                        '<Name>k__BackingField': 'PaymentMethodId',
                        '<Value>k__BackingField': '6',
                      },
                    ],
                  },
                  '<Effects>k__BackingField': {
                    '<Parameters>k__BackingField': [
                      {
                        '<Name>k__BackingField': 'PercentualDiscount',
                        '<Value>k__BackingField': '8.0',
                      },
                    ],
                  },
                },
              ],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 375.77,
              ListPrice: 600.3,
              PriceWithoutDiscount: 375.77,
              RewardValue: 0.0,
              PriceValidUntil: '2023-01-12T13:44:18Z',
              AvailableQuantity: 3000000,
              IsAvailable: true,
              Tax: 0.0,
              SaleChannel: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                '37F62B371F548B5302696581CADC7894_',
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: '1',
                    bin: null,
                    paymentName: 'American Express',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '2',
                    bin: null,
                    paymentName: 'Visa',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 18788,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 18788,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 12525,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 12525,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 4,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 9394,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 4,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 9394,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 5,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 7515,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 5,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 7515,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 6,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 6262,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 6,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 6262,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '3',
                    bin: null,
                    paymentName: 'Diners',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: true,
                        interestRate: 100,
                        value: 19070,
                        total: 38140,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: true,
                            interestRate: 100,
                            value: 19070,
                            total: 38140,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: true,
                        interestRate: 200,
                        value: 13030,
                        total: 39090,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: true,
                            interestRate: 200,
                            value: 13030,
                            total: 39090,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '4',
                    bin: null,
                    paymentName: 'Mastercard',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 18788,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 18788,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 12525,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 12525,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 4,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 9394,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 4,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 9394,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 5,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 7515,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 5,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 7515,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 6,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 6262,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 6,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 6262,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '6',
                    bin: null,
                    paymentName: 'Boleto Bancário',
                    paymentGroupName: 'bankInvoicePaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '16',
                    bin: null,
                    paymentName: 'Vale',
                    paymentGroupName: 'giftCardPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '17',
                    bin: null,
                    paymentName: 'Promissory',
                    paymentGroupName: 'promissoryPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '64',
                    bin: null,
                    paymentName: 'Customer Credit',
                    paymentGroupName: 'creditControlPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 18788,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 18788,
                            total: 37577,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: true,
                        interestRate: 100,
                        value: 12901,
                        total: 38703,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: true,
                            interestRate: 100,
                            value: 12901,
                            total: 38703,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '201',
                    bin: null,
                    paymentName: 'Free',
                    paymentGroupName: 'custom201PaymentGroupPaymentGroup',
                    value: 37577,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 37577,
                        total: 37577,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 37577,
                            total: 37577,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 2,
                    name: 'Visa',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '2',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 4,
                    name: 'Mastercard',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '4',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 17,
                    name: 'Promissory',
                    groupName: 'promissoryPaymentGroup',
                    validator: null,
                    stringId: '17',
                    template: 'promissoryPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:27:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 201,
                    name: 'Free',
                    groupName: 'custom201PaymentGroupPaymentGroup',
                    validator: null,
                    stringId: '201',
                    template: 'custom201PaymentGroupPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: true,
                    description: '',
                    requiresAuthentication: false,
                    dueDate: '2022-01-22T13:27:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 6,
                    name: 'Boleto Bancário',
                    groupName: 'bankInvoicePaymentGroup',
                    validator: null,
                    stringId: '6',
                    template: 'bankInvoicePaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 64,
                    name: 'Customer Credit',
                    groupName: 'creditControlPaymentGroup',
                    validator: null,
                    stringId: '64',
                    template: 'creditControlPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 16,
                    name: 'Vale',
                    groupName: 'giftCardPaymentGroup',
                    validator: null,
                    stringId: '16',
                    template: 'giftCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 3,
                    name: 'Diners',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '3',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: true,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 1,
                    name: 'American Express',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '1',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: [
          'http://vimeo.com/132789775',
          'https://www.youtube.com/watch?v=nmZBaWUN3vc',
        ],
        estimatedDateArrival: null,
      },
      {
        itemId: '4',
        name: 'Black',
        nameComplete: 'Tank Black',
        complementName: '',
        ean: 'code123',
        referenceId: [
          {
            Key: 'RefId',
            Value: 'code1234',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1.0,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: '155643',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155643-#width#-#height#/Frame-2.jpg?v=637411555784670000" width="#width#" height="#height#" alt="Frame-2" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155643/Frame-2.jpg?v=637411555784670000',
            imageText: 'Frame-2',
            imageLastModified: '2020-11-16T20:32:58.4670000Z',
          },
        ],
        Color: ['Black'],
        variations: ['Color'],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://storecomponents.vtexcommercestable.com.br/checkout/cart/add?sku=4&qty=1&seller=1&sc=1&price=60030&cv=37F62B371F548B5302696581CADC7894_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                '0': {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'American Express',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'American Express à vista',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa à vista',
                },
                {
                  Value: 300.15,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 2 vezes sem juros',
                },
                {
                  Value: 200.1,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 3 vezes sem juros',
                },
                {
                  Value: 150.07,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 4,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 4 vezes sem juros',
                },
                {
                  Value: 120.06,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 5,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 5 vezes sem juros',
                },
                {
                  Value: 100.05,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 6,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 6 vezes sem juros',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Diners',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Diners à vista',
                },
                {
                  Value: 304.65,
                  InterestRate: 1.0,
                  TotalValuePlusInterestRate: 609.3,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Diners',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Diners 2 vezes com juros',
                },
                {
                  Value: 208.15,
                  InterestRate: 2.0,
                  TotalValuePlusInterestRate: 624.45,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Diners',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Diners 3 vezes com juros',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard à vista',
                },
                {
                  Value: 300.15,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 2 vezes sem juros',
                },
                {
                  Value: 200.1,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 3 vezes sem juros',
                },
                {
                  Value: 150.07,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 4,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 4 vezes sem juros',
                },
                {
                  Value: 120.06,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 5,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 5 vezes sem juros',
                },
                {
                  Value: 100.05,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 6,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 6 vezes sem juros',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Boleto Bancário',
                  PaymentSystemGroupName: 'bankInvoicePaymentGroup',
                  Name: 'Boleto Bancário à vista',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Vale',
                  PaymentSystemGroupName: 'giftCardPaymentGroup',
                  Name: 'Vale à vista',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Promissory',
                  PaymentSystemGroupName: 'promissoryPaymentGroup',
                  Name: 'Promissory à vista',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit à vista',
                },
                {
                  Value: 300.15,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 2 vezes sem juros',
                },
                {
                  Value: 206.1,
                  InterestRate: 1.0,
                  TotalValuePlusInterestRate: 618.3,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 3 vezes com juros',
                },
                {
                  Value: 600.3,
                  InterestRate: 0.0,
                  TotalValuePlusInterestRate: 600.3,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Free',
                  PaymentSystemGroupName: 'custom201PaymentGroupPaymentGroup',
                  Name: 'Free à vista',
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [
                {
                  '<Name>k__BackingField': '8% Boleto',
                  '<Conditions>k__BackingField': {
                    '<MinimumQuantity>k__BackingField': 0,
                    '<Parameters>k__BackingField': [
                      {
                        '<Name>k__BackingField': 'PaymentMethodId',
                        '<Value>k__BackingField': '6',
                      },
                    ],
                  },
                  '<Effects>k__BackingField': {
                    '<Parameters>k__BackingField': [
                      {
                        '<Name>k__BackingField': 'PercentualDiscount',
                        '<Value>k__BackingField': '8.0',
                      },
                    ],
                  },
                },
              ],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 600.3,
              ListPrice: 1000.5,
              PriceWithoutDiscount: 600.3,
              RewardValue: 0.0,
              PriceValidUntil: '2023-01-12T13:44:18Z',
              AvailableQuantity: 3000000,
              IsAvailable: true,
              Tax: 0.0,
              SaleChannel: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                '37F62B371F548B5302696581CADC7894_',
              PaymentOptions: {
                installmentOptions: [
                  {
                    paymentSystem: '1',
                    bin: null,
                    paymentName: 'American Express',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '2',
                    bin: null,
                    paymentName: 'Visa',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30015,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30015,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 20010,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 20010,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 4,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 15007,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 4,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 15007,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 5,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 12006,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 5,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 12006,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 6,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 10005,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 6,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 10005,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '3',
                    bin: null,
                    paymentName: 'Diners',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: true,
                        interestRate: 100,
                        value: 30465,
                        total: 60930,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: true,
                            interestRate: 100,
                            value: 30465,
                            total: 60930,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: true,
                        interestRate: 200,
                        value: 20815,
                        total: 62445,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: true,
                            interestRate: 200,
                            value: 20815,
                            total: 62445,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '4',
                    bin: null,
                    paymentName: 'Mastercard',
                    paymentGroupName: 'creditCardPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30015,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30015,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 20010,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 20010,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 4,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 15007,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 4,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 15007,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 5,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 12006,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 5,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 12006,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 6,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 10005,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 6,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 10005,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '6',
                    bin: null,
                    paymentName: 'Boleto Bancário',
                    paymentGroupName: 'bankInvoicePaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '16',
                    bin: null,
                    paymentName: 'Vale',
                    paymentGroupName: 'giftCardPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '17',
                    bin: null,
                    paymentName: 'Promissory',
                    paymentGroupName: 'promissoryPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '64',
                    bin: null,
                    paymentName: 'Customer Credit',
                    paymentGroupName: 'creditControlPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 2,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 30015,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 2,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 30015,
                            total: 60030,
                          },
                        ],
                      },
                      {
                        count: 3,
                        hasInterestRate: true,
                        interestRate: 100,
                        value: 20610,
                        total: 61830,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 3,
                            hasInterestRate: true,
                            interestRate: 100,
                            value: 20610,
                            total: 61830,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    paymentSystem: '201',
                    bin: null,
                    paymentName: 'Free',
                    paymentGroupName: 'custom201PaymentGroupPaymentGroup',
                    value: 60030,
                    installments: [
                      {
                        count: 1,
                        hasInterestRate: false,
                        interestRate: 0,
                        value: 60030,
                        total: 60030,
                        sellerMerchantInstallments: [
                          {
                            id: 'STORECOMPONENTS',
                            count: 1,
                            hasInterestRate: false,
                            interestRate: 0,
                            value: 60030,
                            total: 60030,
                          },
                        ],
                      },
                    ],
                  },
                ],
                paymentSystems: [
                  {
                    id: 2,
                    name: 'Visa',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '2',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 4,
                    name: 'Mastercard',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '4',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 17,
                    name: 'Promissory',
                    groupName: 'promissoryPaymentGroup',
                    validator: null,
                    stringId: '17',
                    template: 'promissoryPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:27:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 201,
                    name: 'Free',
                    groupName: 'custom201PaymentGroupPaymentGroup',
                    validator: null,
                    stringId: '201',
                    template: 'custom201PaymentGroupPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: true,
                    description: '',
                    requiresAuthentication: false,
                    dueDate: '2022-01-22T13:27:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 6,
                    name: 'Boleto Bancário',
                    groupName: 'bankInvoicePaymentGroup',
                    validator: null,
                    stringId: '6',
                    template: 'bankInvoicePaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 64,
                    name: 'Customer Credit',
                    groupName: 'creditControlPaymentGroup',
                    validator: null,
                    stringId: '64',
                    template: 'creditControlPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 16,
                    name: 'Vale',
                    groupName: 'giftCardPaymentGroup',
                    validator: null,
                    stringId: '16',
                    template: 'giftCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 3,
                    name: 'Diners',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '3',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: true,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                  {
                    id: 1,
                    name: 'American Express',
                    groupName: 'creditCardPaymentGroup',
                    validator: null,
                    stringId: '1',
                    template: 'creditCardPaymentGroup-template',
                    requiresDocument: false,
                    isCustom: false,
                    description: null,
                    requiresAuthentication: false,
                    dueDate: '2022-01-19T13:26:24.5110675Z',
                    availablePayments: null,
                  },
                ],
                payments: [],
                giftCards: [],
                giftCardMessages: [],
                availableAccounts: [],
                availableTokens: [],
              },
            },
          },
        ],
        Videos: ['https://vimeo.com/132789775'],
        estimatedDateArrival: null,
      },
    ],
    skuSpecifications: [
      {
        field: {
          id: 52,
          name: 'Color',
          isActive: true,
          position: 1,
          type: 'Radio',
        },
        values: [
          {
            id: '219',
            name: 'Black',
            position: 14,
          },
        ],
      },
    ],
  },
]
