export const facetsResponseMock = {
  total: 12,
  pagination: {
    count: 1,
    current: {
      index: 1,
      proxyUrl: 'search/trade-policy/1?query=top&operator=and&fuzzy=0&page=1',
    },
    before: [],
    after: [],
    perPage: 24,
    next: {
      index: 0,
    },
    previous: {
      index: 0,
    },
    first: {
      index: 0,
    },
    last: {
      index: 0,
    },
  },
  sampling: false,
  translated: false,
  locale: 'en-US',
  query: 'top',
  operator: 'and',
  fuzzy: '0',
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'shoes3',
          label: 'shoes3',
          id: '1003',
          originalKey: 'shoes3',
          originalLabel: 'shoes3',
          proxyUrl: '',
        },
        {
          count: 99,
          active: false,
          key: 'shoes1',
          label: 'shoes1',
          id: '1001',
          originalKey: 'shoes1',
          originalLabel: 'shoes1',
          proxyUrl: '',
        },
        {
          count: 99,
          active: true,
          key: 'shoes2',
          label: 'shoes2',
          id: '1002',
          originalKey: 'shoes2',
          originalLabel: 'shoes2',
          proxyUrl: '',
        },
      ],
      active: true,
      key: 'testattribute',
      originalKey: 'testattribute',
      label: 'testattribute',
      originalLabel: 'testattribute',
      type: 'text',
    },
    {
      ids: ['8001'],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'shirt3',
          label: 'shirt3',
          id: '2003',
          originalKey: 'shirt3',
          originalLabel: 'shirt3',
          proxyUrl: '',
        },
        {
          count: 99,
          active: false,
          key: 'shirt1',
          label: 'shirt1',
          id: '2001',
          originalKey: 'shirt1',
          originalLabel: 'shirt1',
          proxyUrl: '',
        },
        {
          count: 99,
          active: true,
          key: 'shirt2',
          label: 'shirt2',
          id: '2002',
          originalKey: 'shirt2',
          originalLabel: 'shirt2',
          proxyUrl: '',
        },
      ],
      active: true,
      key: 'testattribute2',
      originalKey: 'testattribute2',
      label: 'testattribute2',
      originalLabel: 'testattribute2',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: false,
          key: 'item',
          label: 'item',
          id: '3001',
          originalKey: 'item',
          originalLabel: 'item',
          proxyUrl: '',
        },
      ],
      active: false,
      key: 'testattribute3',
      originalKey: 'testattribute3',
      label: 'testattribute3',
      originalLabel: 'testattribute3',
      type: 'text',
    },
  ],
}

export const facetsExpectedResult = {
  facets: [
    {
      name: 'testattribute',
      type: 'TEXT',
      hidden: false,
      quantity: 3,
      values: [
        {
          id: '1003',
          quantity: 99,
          name: 'shoes3',
          key: 'testattribute',
          selected: true,
          value: 'shoes3',
        },
        {
          id: '1001',
          quantity: 99,
          name: 'shoes1',
          key: 'testattribute',
          selected: false,
          value: 'shoes1',
        },
        {
          id: '1002',
          quantity: 99,
          name: 'shoes2',
          key: 'testattribute',
          selected: true,
          value: 'shoes2',
        },
      ],
    },
    {
      name: 'testattribute2',
      type: 'TEXT',
      hidden: false,
      quantity: 3,
      values: [
        {
          id: '2003',
          quantity: 99,
          name: 'shirt3',
          key: 'testattribute2',
          selected: true,
          value: 'shirt3',
        },
        {
          id: '2001',
          quantity: 99,
          name: 'shirt1',
          key: 'testattribute2',
          selected: false,
          value: 'shirt1',
        },
        {
          id: '2002',
          quantity: 99,
          name: 'shirt2',
          key: 'testattribute2',
          selected: true,
          value: 'shirt2',
        },
      ],
    },
    {
      name: 'testattribute3',
      type: 'TEXT',
      hidden: false,
      quantity: 1,
      values: [
        {
          id: '3001',
          quantity: 99,
          name: 'item',
          key: 'testattribute3',
          selected: false,
          value: 'item',
        },
      ],
    },
  ],
  breadcrumb: [
    {
      name: 'top',
      href: '/top?map=ft',
    },
    {
      name: 'shoes3',
      href: '/top/shoes3?map=ft,testattribute',
    },
    {
      name: 'shoes2',
      href: '/top/shoes3/shoes2?map=ft,testattribute,testattribute',
    },
    {
      name: 'shirt3',
      href: '/top/shoes3/shoes2/shirt3?map=ft,testattribute,testattribute,testattribute2',
    },
    {
      name: 'shirt2',
      href: '/top/shoes3/shoes2/shirt3/shirt2?map=ft,testattribute,testattribute,testattribute2,testattribute2',
    },
  ],
  queryArgs: {
    query: 'top',
    selectedFacets: [
      {
        key: 'testattribute',
        value: 'shoes3',
      },
      {
        key: 'testattribute',
        value: 'shoes2',
      },
      {
        key: 'testattribute2',
        value: 'shirt3',
      },
      {
        key: 'testattribute2',
        value: 'shirt2',
      },
      {
        key: 'ft',
        value: 'top',
      },
    ],
  },
}

export const facetsExpectedNavigationResult = {
  facets: [
    {
      name: 'testattribute',
      type: 'TEXT',
      hidden: false,
      quantity: 3,
      values: [
        {
          id: '1003',
          quantity: 99,
          name: 'shoes3',
          key: 'testattribute',
          selected: true,
          value: 'shoes3',
        },
        {
          id: '1001',
          quantity: 99,
          name: 'shoes1',
          key: 'testattribute',
          selected: false,
          value: 'shoes1',
        },
        {
          id: '1002',
          quantity: 99,
          name: 'shoes2',
          key: 'testattribute',
          selected: true,
          value: 'shoes2',
        },
      ],
    },
    {
      name: 'testattribute2',
      type: 'TEXT',
      hidden: false,
      quantity: 3,
      values: [
        {
          id: '2003',
          quantity: 99,
          name: 'shirt3',
          key: 'testattribute2',
          selected: true,
          value: 'shirt3',
        },
        {
          id: '2001',
          quantity: 99,
          name: 'shirt1',
          key: 'testattribute2',
          selected: false,
          value: 'shirt1',
        },
        {
          id: '2002',
          quantity: 99,
          name: 'shirt2',
          key: 'testattribute2',
          selected: true,
          value: 'shirt2',
        },
      ],
    },
    {
      name: 'testattribute3',
      type: 'TEXT',
      hidden: false,
      quantity: 1,
      values: [
        {
          id: '3001',
          quantity: 99,
          name: 'item',
          key: 'testattribute3',
          selected: false,
          value: 'item',
        },
      ],
    },
  ],
  breadcrumb: [
    {
      name: 'shoes3',
      href: '/shoes3?map=testattribute',
    },
    {
      name: 'shoes2',
      href: '/shoes3/shoes2?map=testattribute,testattribute',
    },
    {
      name: 'shirt3',
      href: '/shoes3/shoes2/shirt3?map=testattribute,testattribute,testattribute2',
    },
    {
      name: 'shirt2',
      href: '/shoes3/shoes2/shirt3/shirt2?map=testattribute,testattribute,testattribute2,testattribute2',
    },
  ],
  queryArgs: {
    query: '',
    selectedFacets: [
      {
        key: 'testattribute',
        value: 'shoes3',
      },
      {
        key: 'testattribute',
        value: 'shoes2',
      },
      {
        key: 'testattribute2',
        value: 'shirt3',
      },
      {
        key: 'testattribute2',
        value: 'shirt2',
      },
    ],
  },
}

export const categoryTreeResultMock = {
  name: '',
  type: 'CATEGORYTREE',
  hidden: false,
  quantity: 1,
  facets: [
    {
      id: '4001',
      quantity: 17,
      name: 'My department',
      key: 'c',
      selected: true,
      value: 'my-department',
      children: [
        {
          id: '4002',
          quantity: 1,
          name: '5001',
          key: 'c',
          selected: false,
          value: 'my-category',
          children: [],
        },
      ],
    },
  ],
}

export const facetsWithcategoryResponseMock = {
  total: 12,
  pagination: {
    count: 1,
    current: {
      index: 1,
      proxyUrl: 'search/trade-policy/1?query=top&operator=and&fuzzy=0&page=1',
    },
    before: [],
    after: [],
    perPage: 24,
    next: {
      index: 0,
    },
    previous: {
      index: 0,
    },
    first: {
      index: 0,
    },
    last: {
      index: 0,
    },
  },
  sampling: false,
  translated: false,
  locale: 'en-US',
  query: 'top',
  operator: 'and',
  fuzzy: '0',
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'my-department',
          label: 'my-department',
          id: '4001',
          originalKey: 'my-department',
          originalLabel: 'my-department',
          proxyUrl: '',
        },
      ],
      active: true,
      key: 'category-1',
      originalKey: 'category-1',
      label: 'department',
      originalLabel: 'department',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: false,
          key: 'my-category',
          label: 'my-category',
          id: '5001',
          originalKey: 'my-category',
          originalLabel: 'my-category',
          proxyUrl: '',
        },
      ],
      active: false,
      key: 'category-2',
      originalKey: 'category-2',
      label: 'category',
      originalLabel: 'category',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: false,
          key: 'red',
          label: 'red',
          id: '6001',
          originalKey: 'red',
          originalLabel: 'red',
          proxyUrl: '',
        },
      ],
      active: false,
      key: 'color',
      originalKey: 'color',
      label: 'color',
      originalLabel: 'color',
      type: 'text',
    },
  ],
}

export const facetsCatalogResponseMock = {
  CategoriesTrees: [
    {
      Id: 4001,
      Quantity: 99,
      Position: null,
      Name: 'my-department',
      Link: '/my-department?map=c',
      LinkEncoded: '/my-department?map=c',
      Map: 'c',
      Value: 'my-department',
      Children: [
        {
          Id: 5001,
          Quantity: 99,
          Position: null,
          Name: 'my-category',
          Link: '/my-department/my-category?map=c,c',
          LinkEncoded: '/my-department/my-category?map=c,c',
          Map: 'c',
          Value: 'my-category',
          Children: [],
        },
      ],
    },
  ],
}

export const listBycategoryResponseMock = [
  {
    Name: 'color',
    CategoryId: 4001,
    FieldId: 7001,
    IsActive: true,
    IsStockKeepingUnit: true,
  },
]

export const getFieldResponseMock = {
  Name: 'color',
  CategoryId: 11,
  FieldId: 7001,
  IsActive: true,
  IsRequired: false,
  FieldTypeId: 5,
  FieldTypeName: 'Combo',
  FieldValueId: null,
  Description: 'dasds',
  IsStockKeepingUnit: false,
  IsFilter: false,
  IsOnProductDetails: true,
  Position: 1,
  IsWizard: false,
  IsTopMenuLinkActive: true,
  IsSideMenuLinkActive: false,
  DefaultValue: null,
  FieldGroupId: 11,
  FieldGroupName: 'Group',
}

export const setVisibilityExpecteResult = {
  facets: [
    {
      values: [
        {
          id: '4001',
          quantity: 99,
          name: 'my-department',
          key: 'category-1',
          value: 'my-department',
          selected: true,
          href: 'my-department/my-department?map=category-1',
        },
      ],
      type: 'TEXT',
      name: 'department',
      hidden: false,
      quantity: 1,
    },
    {
      values: [
        {
          id: '5001',
          quantity: 99,
          name: 'my-category',
          key: 'category-2',
          value: 'my-category',
          selected: false,
          href: 'my-department/my-category?map=category-2',
        },
      ],
      type: 'TEXT',
      name: 'category',
      hidden: false,
      quantity: 1,
    },
    {
      values: [
        {
          id: '6001',
          quantity: 99,
          name: 'red',
          key: 'color',
          value: 'red',
          selected: false,
          href: 'my-department/red?map=color',
        },
      ],
      type: 'TEXT',
      name: 'color',
      hidden: true,
      quantity: 1,
    },
  ],
  sampling: false,
  breadcrumb: [{ name: 'my-department', href: '/my-department' }],
  queryArgs: {
    query: '',
    selectedFacets: [{ key: 'c', value: 'my-department' }],
  },
}

export const getFieldValuesResponseMock = [
  {
    FieldValueId: 2001,
    Value: 'shirt1',
    IsActive: true,
    Position: 1,
  },
  {
    FieldValueId: 2002,
    Value: 'shirt2',
    IsActive: true,
    Position: 2,
  },
  {
    FieldValueId: 2003,
    Value: 'shirt3',
    IsActive: true,
    Position: 3,
  },
]

export const facetsAfterSortExpectedResult = {
  facets: [
    {
      name: 'testattribute',
      type: 'TEXT',
      hidden: false,
      quantity: 3,
      values: [
        {
          id: '1003',
          quantity: 99,
          name: 'shoes3',
          key: 'testattribute',
          selected: true,
          value: 'shoes3',
        },
        {
          id: '1001',
          quantity: 99,
          name: 'shoes1',
          key: 'testattribute',
          selected: false,
          value: 'shoes1',
        },
        {
          id: '1002',
          quantity: 99,
          name: 'shoes2',
          key: 'testattribute',
          selected: true,
          value: 'shoes2',
        },
      ],
    },
    {
      name: 'testattribute2',
      type: 'TEXT',
      hidden: false,
      quantity: 3,
      values: [
        {
          id: '2002',
          quantity: 99,
          name: 'shirt2',
          key: 'testattribute2',
          selected: true,
          value: 'shirt2',
        },
        {
          id: '2003',
          quantity: 99,
          name: 'shirt3',
          key: 'testattribute2',
          selected: true,
          value: 'shirt3',
        },
        {
          id: '2001',
          quantity: 99,
          name: 'shirt1',
          key: 'testattribute2',
          selected: false,
          value: 'shirt1',
        },
      ],
    },
    {
      name: 'testattribute3',
      type: 'TEXT',
      hidden: false,
      quantity: 1,
      values: [
        {
          id: '3001',
          quantity: 99,
          name: 'item',
          key: 'testattribute3',
          selected: false,
          value: 'item',
        },
      ],
    },
  ],
}

export const facetsMockBreadcrumb = {
  total: 12,
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'shirts1',
          label: 'shirts1',
          id: '1001',
          originalKey: 'shirts1',
          originalLabel: 'shirts1',
        },
      ],
      active: true,
      key: 'shirts',
      originalKey: 'shirts',
      label: 'shirts',
      originalLabel: 'shirts',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'shoes3',
          label: 'shoes3',
          id: '1003',
          originalKey: 'shoes3',
          originalLabel: 'shoes3',
        },
        {
          count: 99,
          active: false,
          key: 'shoes1',
          label: 'shoes1',
          id: '1001',
          originalKey: 'shoes1',
          originalLabel: 'shoes1',
        },
        {
          count: 99,
          active: true,
          key: 'shoes2',
          label: 'shoes2',
          id: '1002',
          originalKey: 'shoes2',
          originalLabel: 'shoes2',
        },
      ],
      active: true,
      key: 'shoes',
      originalKey: 'shoes',
      label: 'shoes',
      originalLabel: 'shoes',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'sharedvalue',
          label: 'sharedvalue',
          id: '1001',
          originalKey: 'sharedvalue',
          originalLabel: 'sharedvalue',
        },
      ],
      active: true,
      key: 'category-1',
      originalKey: 'category-1',
      label: 'department',
      originalLabel: 'department',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'sharedvalue',
          label: 'sharedvalue',
          id: '1001',
          originalKey: 'sharedvalue',
          originalLabel: 'sharedvalue',
        },
      ],
      active: true,
      key: 'category-3',
      originalKey: 'category-3',
      label: 'subcategory',
      originalLabel: 'subcategory',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'value',
          label: 'value',
          id: '1001',
          originalKey: 'value',
          originalLabel: 'value',
        },
      ],
      active: true,
      key: 'category-2',
      originalKey: 'category-2',
      label: 'category',
      originalLabel: 'category',
      type: 'text',
    },
  ],
}

export const facetsMockBreadcrumbWithLocation = {
  total: 12,
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'camisas1',
          label: 'camisas1',
          id: '1001',
          originalKey: 'shirts1',
          originalLabel: 'shirts1',
        },
      ],
      active: true,
      key: 'camisas',
      originalKey: 'shirts',
      label: 'camisas',
      originalLabel: 'shirts',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'sapatos3',
          label: 'sapatos3',
          id: '1003',
          originalKey: 'shoes3',
          originalLabel: 'shoes3',
        },
        {
          count: 99,
          active: false,
          key: 'sapatos1',
          label: 'sapatos1',
          id: '1001',
          originalKey: 'shoes1',
          originalLabel: 'shoes1',
        },
        {
          count: 99,
          active: true,
          key: 'sapatos2',
          label: 'sapatos2',
          id: '1002',
          originalKey: 'shoes2',
          originalLabel: 'shoes2',
        },
      ],
      active: true,
      key: 'sapatos',
      originalKey: 'shoes',
      label: 'sapatos',
      originalLabel: 'shoes',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'valorcompartilhado',
          label: 'valorcompartilhado',
          id: '1001',
          originalKey: 'sharedvalue',
          originalLabel: 'sharedvalue',
        },
      ],
      active: true,
      key: 'category-1',
      originalKey: 'category-1',
      label: 'department',
      originalLabel: 'department',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'valorcompartilhado',
          label: 'valorcompartilhado',
          id: '1001',
          originalKey: 'sharedvalue',
          originalLabel: 'sharedvalue',
        },
      ],
      active: true,
      key: 'category-3',
      originalKey: 'category-3',
      label: 'subcategory',
      originalLabel: 'subcategory',
      type: 'text',
    },
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'valor',
          label: 'valor',
          id: '1001',
          originalKey: 'value',
          originalLabel: 'value',
        },
      ],
      active: true,
      key: 'category-2',
      originalKey: 'category-2',
      label: 'category',
      originalLabel: 'category',
      type: 'text',
    },
  ],
}

export const facetsMockBreadcrumbWithProductClusterIds = {
  total: 12,
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'camisas1',
          label: 'camisas1',
          id: '1001',
          originalKey: 'shirts1',
          originalLabel: 'shirts1',
        },
      ],
      active: true,
      key: 'camisas',
      originalKey: 'shirts',
      label: 'camisas',
      originalLabel: 'shirts',
      type: 'text',
    },
    {
      ids: [],
      visible: false,
      values: [
        {
          count: 99,
          active: true,
          key: '123',
          label: '123',
          id: '1001',
          originalKey: '123',
          originalLabel: '123',
        },
      ],
      active: true,
      key: 'productclusterids',
      originalKey: 'productclusterids',
      label: 'productclusterIds',
      originalLabel: 'productclusterIds',
      type: 'text',
    },
  ],
}

export const facetsMockBreadcrumbWithProductClusterNames = {
  total: 12,
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'camisas1',
          label: 'camisas1',
          id: '1001',
          originalKey: 'shirts1',
          originalLabel: 'shirts1',
        },
      ],
      active: true,
      key: 'camisas',
      originalKey: 'shirts',
      label: 'camisas',
      originalLabel: 'shirts',
      type: 'text',
    },
    {
      ids: [],
      visible: false,
      values: [
        {
          count: 99,
          active: true,
          key: 'MyClusterName',
          label: 'MyClusterName',
          id: '1001',
          originalKey: 'MyClusterName',
          originalLabel: 'MyClusterName',
        },
      ],
      active: true,
      key: 'productclusternames',
      originalKey: 'productclusternames',
      label: 'productclusterNames',
      originalLabel: 'productclusterNames',
      type: 'text',
    },
  ],
}

export const facetsMockBreadcrumbWithMultipleProductClusterNames = {
  total: 12,
  attributes: [
    {
      ids: [],
      visible: true,
      values: [
        {
          count: 99,
          active: true,
          key: 'camisas1',
          label: 'camisas1',
          id: '1001',
          originalKey: 'shirts1',
          originalLabel: 'shirts1',
        },
      ],
      active: true,
      key: 'camisas',
      originalKey: 'shirts',
      label: 'camisas',
      originalLabel: 'shirts',
      type: 'text',
    },
    {
      ids: [],
      visible: false,
      values: [
        {
          count: 99,
          active: true,
          key: 'MyClusterName',
          label: 'MyClusterName',
          id: '1001',
          originalKey: 'MyClusterName',
          originalLabel: 'MyClusterName',
        },
        {
          count: 99,
          active: true,
          key: 'MyClusterName2',
          label: 'MyClusterName2',
          id: '1002',
          originalKey: 'MyClusterName2',
          originalLabel: 'MyClusterName2',
        },
      ],
      active: true,
      key: 'productclusternames',
      originalKey: 'productclusternames',
      label: 'productclusterNames',
      originalLabel: 'productclusterNames',
      type: 'text',
    },
  ],
}
